from enum import Enum

class ResponseSignal(Enum):
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_VALID = "FILE_VALID"
    UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
    UPLOAD_FAILURE = "UPLOAD_FAILURE"
    FILE_VALIDATION_ERROR = "FILE_VALIDATION_ERROR"