from enum import Enum

class ResponseSignal(Enum):
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_VALID = "FILE_VALID"
    UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
    UPLOAD_FAILURE = "UPLOAD_FAILURE"
    FILE_VALIDATION_ERROR = "FILE_VALIDATION_ERROR"
    FILE_PROCESSING_FAILURE = "FILE_PROCESSING_FAILURE"
    FILE_PROCESSING_SUCCESS = "FILE_PROCESSING_SUCCESS"
    NO_FILES_TO_PROCESS = "NO_FILES_TO_PROCESS"
    NO_FILES_FOUND_WITH_THIS_ID = "NO_FILES_FOUND_WITH_THIS_ID"